# Google Android Management API Properties
google.android.management.enterprise-id=LC024ke615
google.android.management.policy-id=default
google.android.management.service-account-path=service-account.json
